services:
  lmarena-imagen-automator:
    image: foxhui/lmarena-imagen-automator:latest
    container_name: lmarena-imagen-automator
    restart: unless-stopped
    ports:
      - "3000:3000" # API
      - "5900:5900" # VNC
    volumes:
      # 配置文件会自动生成到这里：./data/config.yaml
      - ./data:/app/data
    environment:
      - DISPLAY=:99
      # false: 标准挂机模式
      # true: 登录第一个 worker
      # workerName: 只登录指定的 worker
      - LOGIN_MODE=false
    shm_size: '2gb'
    init: true